<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>1.3.1</Version>
    <AssemblyVersion>1.3.1.0</AssemblyVersion>
    <FileVersion>1.3.1.0</FileVersion>
    <InformationalVersion>1.3.1</InformationalVersion>
    <Company>Moon Labs UG (haftungsbeschränkt)</Company>
    <Copyright>Copyright © 2026 Moon Labs UG (haftungsbeschränkt)</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
